Path Limit chnages
dell/gocsi pull request #10
Opened 2022-04-27 05:16 UTC by meggm

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2022-04-27 10:19 UTC, randeepsharma commented on middleware/specvalidator/spec_validator.go
> +						maxPathLimit, found := os.LookupEnv(MaxPathLimit)
this looks cluttered.  create a func and call that func here.

2022-04-27 10:19 UTC, randeepsharma commented on middleware/specvalidator/spec_validator.go
> +						if found {
can have if found && maxPathLimit != "" in a single condition

2022-04-27 10:20 UTC, randeepsharma commented on middleware/specvalidator/spec_validator.go
> +									return status.Errorf(
if err we could log the error and continue to use the default value.

2022-04-27 10:21 UTC, randeepsharma commented on middleware/specvalidator/spec_validator.go
> +						maxPathLimit, found := os.LookupEnv(MaxPathLimit)
also log the length that we get, It could help incase customer keeps a arbitrarily high number.

2022-05-04 03:30 UTC, randeepsharma approved these changes
LGTM

2022-05-04 09:23 UTC, randeepsharma commented on middleware/specvalidator/spec_validator.go
> +	return pathLimit
This could lead to pathLimit be 0 , if not set and everything to fail.
we can avoid the else condition in outer if check.

2022-05-04 09:24 UTC, randeepsharma requested changes
Fix the return to have default value if the path limit is not set.

2022-05-05 05:20 UTC, randeepsharma approved these changes

2022-05-05 05:55 UTC, bpjain2004 commented on middleware/specvalidator/spec_validator.go
> +	MaxPathLimit = "X_CSI_MAX_PATH_LIMIT"
No need to export this variable if you want to use it only in this package.
Also, you may want to rename this to EnvVarMaxPathLimit and move it to https://github.com/dell/gocsi/blob/main/envvars.go. Please check.

2022-05-09 05:34 UTC, meggm commented on middleware/specvalidator/spec_validator.go
> +	MaxPathLimit = "X_CSI_MAX_PATH_LIMIT"
Fixed the comments

2022-05-09 05:35 UTC, randeepsharma approved these changes

2022-05-11 15:59 UTC, JacobGros approved these changes
Looks good to me. 
Built and tested w/ PowerFlex. 
How are we handling these changes driver side? Are we adding a param to values.yaml? 
Thanks

2022-05-11 16:36 UTC, meggm commented
> Looks good to me. Built and tested w/ PowerFlex. How are we handling these changes driver side? Are we adding a param to values.yaml? Thanks

Yes, This parameter will be added in the values.yaml file

2022-05-12 02:41 UTC, merged